name: database

services:
  postgres:
    image: ${IMAGE_POSTGIS}
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - apps
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      start_interval: 10s
      start_period: 1s

  # jdbc:oracle:thin:@//localhost:1521/FREEPDB1
  # username: SYSTEM
  # password: oracle
  oracle:
    image: ${IMAGE_ORACLE}
    container_name: oracle
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle

volumes:
  postgres_data:
    driver: local
  oracle_data:
    driver: local