name: database

services:
  postgres:
    image: ${IMAGE_POSTGIS}
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - apps
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      start_interval: 10s
      start_period: 1s

  # jdbc:oracle:thin:@//localhost:1521/FREEPDB1
  # username: SYSTEM
  # password: oracle
  oracle:
    image: ${IMAGE_ORACLE}
    container_name: oracle
    volumes:
      - oracle_data:/opt/oracle/oradata
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle

  mongo:
    image: ${IMAGE_MONGO}
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: ${IMAGE_MONGO_EXPRESS}
    container_name: mongo-express
    restart: always
    ports:
      - "8071:8081"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH_ENABLED: true
      ME_CONFIG_BASICAUTH_USERNAME: mongoexpressuser
      ME_CONFIG_BASICAUTH_PASSWORD: mongoexpresspass

volumes:
  postgres_data:
    driver: local
  oracle_data:
    driver: local
  mongo_data:
    driver: local