name: database

services:
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    ports:
      - "9000:9000"  # API port
      - "9001:9001"  # Console port
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

    # Optional: Add a MinIO client for administration
  mc:
    image: minio/mc
    container_name: mc
    depends_on:
      - minio
    environment:
      - MC_HOST_minio=http://minioadmin:minioadmin@minio:9000
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc ls minio); do echo 'Waiting for MinIO...'; sleep 1; done;
      /usr/bin/mc mb minio/my-bucket;
      /usr/bin/mc policy set public minio/my-bucket;
      echo 'MinIO client configured!';
      tail -f /dev/null
      "

volumes:
  minio_data:
    driver: local
