name: database
  
  
  docker run -d --name n8n -p 5678:5678 `
  -e WEBHOOK_URL=https://yourdomain.com `
  -e N8N_DEFAULT_BINARY_DATA_MODE=filesystem `
  -v C:\Docker\n8n-data:/home/node/.n8n `
  docker.n8n.io/n8nio/n8n
services:
  n8n:
    image: ${IMAGE_N8N}
    container_name: n8n
    volumes:
      - n8n_data:/home/node/.n8n
    ports:
      - "${N8N_PORT}:5678"
    environment:
      N8N_RUNNERS_ENABLED: true
      N8N_DEFAULT_BINARY_DATA_MODE: filesystem
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: ${N8N_DB_NAME}
      DB_POSTGRESDB_USER: ${N8N_DB_USERNAME}
      DB_POSTGRESDB_PASSWORD: ${N8N_DB_USERNAME}
    networks:
      - apps

volumes:
  n8n_data:
    driver: local
