name: database

services:

  # Download *.osm.pbf data from https://download.geofabrik.de/
  nominatim:
    image: ${IMAGE_NOMINATIM}
    container_name: nominatim
    volumes:
      - ./navigation:/navigation
    ports:
      - "9090:8080"
    environment:
      THREADS: 8
      PBF_PATH: /navigation/iran-latest.osm.pbf
      NOMINATIM_TOKENIZER: icu
      NOMINATIM_DATABASE_DSN: "pgsql:dbname=nominatim;host=172.17.0.2;user=postgres;password=postgres"
      PGHOSTADDR: 172.17.0.2
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: nominatim
      PGUSER: postgres
      PGPASSWORD: postgres
      NOMINATIM_PASSWORD: navigation_user

    networks:
      - apps

volumes:
  nominatim:
    driver: local
