CREATE USER PREPAID_CARD_BACKEND IDENTIFIED BY 12345678
    QUOTA 1000M ON users;
GRANT CREATE SESSION TO PREPAID_CARD_BACKEND;
GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO PREPAID_CARD_BACKEND;
